import Blog1 from '../assets/images/blog1.png'
import Blog2 from '../assets/images/blog2.png'
import Blog3 from '../assets/images/blog3.png'
import Detail1 from '../assets//images/bd1.png'

export const blogDatas = [
    {
        blogSlug: "UI-UX",
        cat: "UI/UX",
        imgUrl: Blog1,
        detailimg: Detail1,
        title: "How does design thinking work and what does it entail?",
        sub: "Lorem Ipsum has been the industry's standard dummy text ever since.",
        detail1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit proin mi pellentesque lorem turpis feugiat non sed sed sed aliquam lectus sodales gravida turpis maassa odio. we'll explore the importance of design in the software development process and how it can lead to more successful projects.",
        detail2: "Lorem ipsum dolor sit amet consectetur. Ipsum vitae tincidunt adipiscing sed tellus nulla sit ultrices. Arcu maecenas quam iaculis ullamcorper id posuere. Leo congue nulla quam pharetra. Pellentesque morbi dictumst congue risus luctus. Dictum eu maecenas ipsum dolor vel imperdiet. Euismod fermentum sed quisque risus malesuada molestie. Aliquam ut vel penatibus eu sit in egestas molestie nisl. Interdum euismod mattis euismod vulputate non.",
        tag:["Design", "UI/UX", "Landing Page", "Website", "App Design", "Finance"],
    }, 
    {
        blogSlug: "web-development",
        cat: "Web Development",
        imgUrl: Blog2,
        detailimg: Detail1,
        title: "How does design thinking work and what does it entail?",
        sub: "Lorem Ipsum has been the industry's standard dummy text ever since.",
        detail1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit proin mi pellentesque lorem turpis feugiat non sed sed sed aliquam lectus sodales gravida turpis maassa odio. we'll explore the importance of design in the software development process and how it can lead to more successful projects.",
        detail2: "Lorem ipsum dolor sit amet consectetur. Ipsum vitae tincidunt adipiscing sed tellus nulla sit ultrices. Arcu maecenas quam iaculis ullamcorper id posuere. Leo congue nulla quam pharetra. Pellentesque morbi dictumst congue risus luctus. Dictum eu maecenas ipsum dolor vel imperdiet. Euismod fermentum sed quisque risus malesuada molestie. Aliquam ut vel penatibus eu sit in egestas molestie nisl. Interdum euismod mattis euismod vulputate non.",
        tag:["Web Development", "Landing Page", "Website", "App Design", "Finance"],
    },
    {
        blogSlug: "app-design",
        cat: "App Design",
        imgUrl: Blog3,
        detailimg: Detail1,
        title: "How does design thinking work and what does it entail?",
        sub: "Lorem Ipsum has been the industry's standard dummy text ever since.",
        detail1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit proin mi pellentesque lorem turpis feugiat non sed sed sed aliquam lectus sodales gravida turpis maassa odio. we'll explore the importance of design in the software development process and how it can lead to more successful projects.",
        detail2: "Lorem ipsum dolor sit amet consectetur. Ipsum vitae tincidunt adipiscing sed tellus nulla sit ultrices. Arcu maecenas quam iaculis ullamcorper id posuere. Leo congue nulla quam pharetra. Pellentesque morbi dictumst congue risus luctus. Dictum eu maecenas ipsum dolor vel imperdiet. Euismod fermentum sed quisque risus malesuada molestie. Aliquam ut vel penatibus eu sit in egestas molestie nisl. Interdum euismod mattis euismod vulputate non.",
        tag:[ "App Design", "Landing Page", "Website", "Finance"],
    },
    {
        blogSlug: "app-design1",
        cat: "App Design",
        imgUrl: Blog3,
        detailimg: Detail1,
        title: "How does design thinking work and what does it entail?",
        sub: "Lorem Ipsum has been the industry's standard dummy text ever since.",
        detail1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit proin mi pellentesque lorem turpis feugiat non sed sed sed aliquam lectus sodales gravida turpis maassa odio. we'll explore the importance of design in the software development process and how it can lead to more successful projects.",
        detail2: "Lorem ipsum dolor sit amet consectetur. Ipsum vitae tincidunt adipiscing sed tellus nulla sit ultrices. Arcu maecenas quam iaculis ullamcorper id posuere. Leo congue nulla quam pharetra. Pellentesque morbi dictumst congue risus luctus. Dictum eu maecenas ipsum dolor vel imperdiet. Euismod fermentum sed quisque risus malesuada molestie. Aliquam ut vel penatibus eu sit in egestas molestie nisl. Interdum euismod mattis euismod vulputate non.",
        tag:[ "App Design", "Landing Page", "Website", "Finance"],
    },
    {
        blogSlug: "app-design2",
        cat: "App Design",
        imgUrl: Blog3,
        detailimg: Detail1,
        title: "How does design thinking work and what does it entail?",
        sub: "Lorem Ipsum has been the industry's standard dummy text ever since.",
        detail1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit proin mi pellentesque lorem turpis feugiat non sed sed sed aliquam lectus sodales gravida turpis maassa odio. we'll explore the importance of design in the software development process and how it can lead to more successful projects.",
        detail2: "Lorem ipsum dolor sit amet consectetur. Ipsum vitae tincidunt adipiscing sed tellus nulla sit ultrices. Arcu maecenas quam iaculis ullamcorper id posuere. Leo congue nulla quam pharetra. Pellentesque morbi dictumst congue risus luctus. Dictum eu maecenas ipsum dolor vel imperdiet. Euismod fermentum sed quisque risus malesuada molestie. Aliquam ut vel penatibus eu sit in egestas molestie nisl. Interdum euismod mattis euismod vulputate non.",
        tag:[ "App Design", "Landing Page", "Website", "Finance"],
    },
    {
        blogSlug: "app-design3",
        cat: "App Design",
        imgUrl: Blog3,
        detailimg: Detail1,
        title: "How does design thinking work and what does it entail?",
        sub: "Lorem Ipsum has been the industry's standard dummy text ever since.",
        detail1:"Lorem ipsum dolor sit amet, consectetur adipiscing elit proin mi pellentesque lorem turpis feugiat non sed sed sed aliquam lectus sodales gravida turpis maassa odio. we'll explore the importance of design in the software development process and how it can lead to more successful projects.",
        detail2: "Lorem ipsum dolor sit amet consectetur. Ipsum vitae tincidunt adipiscing sed tellus nulla sit ultrices. Arcu maecenas quam iaculis ullamcorper id posuere. Leo congue nulla quam pharetra. Pellentesque morbi dictumst congue risus luctus. Dictum eu maecenas ipsum dolor vel imperdiet. Euismod fermentum sed quisque risus malesuada molestie. Aliquam ut vel penatibus eu sit in egestas molestie nisl. Interdum euismod mattis euismod vulputate non.",
        tag:[ "App Design", "Landing Page", "Website", "Finance"],
    },
]