import Slider1 from '../assets/images/slider1.png'
import Slider2 from '../assets/images/port2.png'
import Slider3 from '../assets/images/port3.png'
import Slider4 from '../assets/images/port4.png'
import Slider5 from '../assets/images/port5.png'
import Slider6 from '../assets/images/port6.png'
import Slider7 from '../assets/images/port7.png'
import Slider8 from '../assets/images/port8.png'


export const projectDatas = [
    {
        slug: "finTech-ui",
        imgPro: Slider1,
        detailImg: Slider3,
        titlePro: "UI/UX Design",
        companyName: "Fintech Website UI/UX",
        projectDetails1: "I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectDetails2:"I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectSummary: "Certainly, I'd be happy to help you with a fintech portfolio project summary. However, I'll need a bit more information about the specific details of your project. Fintech (financial technology) is a broad field that covers various aspects of using technology to enhance and innovate financial services. Could you please provide more context about your project?",
        clientReview: "Lorem ipsum dolor sit amet consectetur. consectetur lorem auctor volutpat rhoncus nulla.",
        clientName: "Esabela Marun",
        category: "UI/UX Design",
        date: "June, 2023",
        summeryList: [
            "(B2B) Buying",
            "Demographic data",
            "Occoecat velt Dis! ea wisi",
            "Demographic data",
            "Fintech Marketing",
            "Dignissimos quod arnare fugit.",
        ],
      
    },
    {
        slug: "nft-mobile",
        imgPro: Slider2,
        detailImg: Slider3,
        titlePro: "Development",
        companyName: "NFT Mobile App Design",
        projectDetails1: "I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectDetails2:"I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectSummary: "Certainly, I'd be happy to help you with a fintech portfolio project summary. However, I'll need a bit more information about the specific details of your project. Fintech (financial technology) is a broad field that covers various aspects of using technology to enhance and innovate financial services. Could you please provide more context about your project?",
        clientReview: "Lorem ipsum dolor sit amet consectetur. consectetur lorem auctor volutpat rhoncus nulla.",
        clientName: "Esabela Marun",
        category: "UI/UX Design",
        date: "June, 2023",
        summeryList: [
            "(B2B) Buying",
            "Demographic data",
            "Occoecat velt Dis! ea wisi",
            "Demographic data",
            "Fintech Marketing",
            "Dignissimos quod arnare fugit.",
        ],

    },
    {
        slug: "finance-saas",
        imgPro: Slider3,
        detailImg: Slider3,
        titlePro: "Finance",
        companyName: "Fintech Saas Website",
        projectDetails1: "I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectDetails2:"I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectSummary: "Certainly, I'd be happy to help you with a fintech portfolio project summary. However, I'll need a bit more information about the specific details of your project. Fintech (financial technology) is a broad field that covers various aspects of using technology to enhance and innovate financial services. Could you please provide more context about your project?",
        clientReview: "Lorem ipsum dolor sit amet consectetur. consectetur lorem auctor volutpat rhoncus nulla.",
        clientName: "Esabela Marun",
        category: "UI/UX Design",
        date: "June, 2023",
        summeryList: [
            "(B2B) Buying",
            "Demographic data",
            "Occoecat velt Dis! ea wisi",
            "Demographic data",
            "Fintech Marketing",
            "Dignissimos quod arnare fugit.",
        ],
    },
    {
        slug: 'real-estate',
        imgPro: Slider4,
        detailImg: Slider3,
        titlePro: "UI Design",
        companyName: "Real Estate App Design",
        projectDetails1: "I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectDetails2:"I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectSummary: "Certainly, I'd be happy to help you with a fintech portfolio project summary. However, I'll need a bit more information about the specific details of your project. Fintech (financial technology) is a broad field that covers various aspects of using technology to enhance and innovate financial services. Could you please provide more context about your project?",
        clientReview: "Lorem ipsum dolor sit amet consectetur. consectetur lorem auctor volutpat rhoncus nulla.",
        clientName: "Esabela Marun",
        category: "UI/UX Design",
        date: "June, 2023",
        summeryList: [
            "(B2B) Buying",
            "Demographic data",
            "Occoecat velt Dis! ea wisi",
            "Demographic data",
            "Fintech Marketing",
            "Dignissimos quod arnare fugit.",
        ],
    },
    {
        slug: 'task-management',
        imgPro: Slider5,
        detailImg: Slider3,
        titlePro: "Web Development",
        companyName: "Task Management",
        projectDetails1: "I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectDetails2:"I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectSummary: "Certainly, I'd be happy to help you with a fintech portfolio project summary. However, I'll need a bit more information about the specific details of your project. Fintech (financial technology) is a broad field that covers various aspects of using technology to enhance and innovate financial services. Could you please provide more context about your project?",
        clientReview: "Lorem ipsum dolor sit amet consectetur. consectetur lorem auctor volutpat rhoncus nulla.",
        clientName: "Esabela Marun",
        category: "UI/UX Design",
        date: "June, 2023",
        summeryList: [
            "(B2B) Buying",
            "Demographic data",
            "Occoecat velt Dis! ea wisi",
            "Demographic data",
            "Fintech Marketing",
            "Dignissimos quod arnare fugit.",
        ],
    },
    {
        slug: 'admin-pannel',
        imgPro: Slider6,
        detailImg: Slider3,
        titlePro: "UI/UX Design",
        companyName: "Admin Panel Desgin",
        projectDetails1: "I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectDetails2:"I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectSummary: "Certainly, I'd be happy to help you with a fintech portfolio project summary. However, I'll need a bit more information about the specific details of your project. Fintech (financial technology) is a broad field that covers various aspects of using technology to enhance and innovate financial services. Could you please provide more context about your project?",
        clientReview: "Lorem ipsum dolor sit amet consectetur. consectetur lorem auctor volutpat rhoncus nulla.",
        clientName: "Esabela Marun",
        category: "UI/UX Design",
        date: "June, 2023",
        summeryList: [
            "(B2B) Buying",
            "Demographic data",
            "Occoecat velt Dis! ea wisi",
            "Demographic data",
            "Fintech Marketing",
            "Dignissimos quod arnare fugit.",
        ],
    },
    {
        slug: 'degital-agency',
        imgPro: Slider7,
        detailImg: Slider3,
        titlePro: "UI/UX Design",
        companyName: "Digital Agency Website",
        projectDetails1: "I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectDetails2:"I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",

        projectSummary: "Certainly, I'd be happy to help you with a fintech portfolio project summary. However, I'll need a bit more information about the specific details of your project. Fintech (financial technology) is a broad field that covers various aspects of using technology to enhance and innovate financial services. Could you please provide more context about your project?",
        clientReview: "Lorem ipsum dolor sit amet consectetur. consectetur lorem auctor volutpat rhoncus nulla.",
        clientName: "Esabela Marun",
        category: "UI/UX Design",
        date: "June, 2023",
        summeryList: [
            "(B2B) Buying",
            "Demographic data",
            "Occoecat velt Dis! ea wisi",
            "Demographic data",
            "Fintech Marketing",
            "Dignissimos quod arnare fugit.",
        ],
    },
    {
        slug: 'app-development',
        imgPro: Slider8,
        detailImg: Slider3,
        titlePro: "App Development",
        companyName: "Apps Development",
        projectDetails1: "I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectDetails2:"I'd be happy to help you with your fintech portfolio project! However, since you haven't provided specific details about the project, I'll give you a general outline of what you might consider including in your fintech portfolio project. If you have specific requirements or aspects you'd like to focus on, please provide more information so I can tailor my response accordingly.",
        projectSummary: "Certainly, I'd be happy to help you with a fintech portfolio project summary. However, I'll need a bit more information about the specific details of your project. Fintech (financial technology) is a broad field that covers various aspects of using technology to enhance and innovate financial services. Could you please provide more context about your project?",
        clientReview: "Lorem ipsum dolor sit amet consectetur. consectetur lorem auctor volutpat rhoncus nulla.",
        clientName: "Esabela Marun",
        category: "UI/UX Design",
        date: "June, 2023",
        summeryList: [
            "(B2B) Buying",
            "Demographic data",
            "Occoecat velt Dis! ea wisi",
            "Demographic data",
            "Fintech Marketing",
            "Dignissimos quod arnare fugit.",
        ],
    },
]